name: Build and test termux-elf-cleaner

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install cmake ninja-build
      - name: Build
        run: |
          cmake . -Bbuild -GNinja
          ninja -C build/
      - name: Test
        run: |
          ninja -C build/ test
